#!/usr/bin/env bash
# Installing and starting nginx
sudo apt update
sudo apt install -y nginx

# Changing html response
echo "Hello World" | tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
