#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20
# 4 = bad luck from China, 9 = bad luck from Japan,
# 17 = bad luck from Italy
i=1
while [ "$i" != 21 ]
do
	case $i in

		4)
			echo $i
			echo "bad luck from China"
			;;

		9)
			echo $i
			echo "bad luck from Japan"
			;;

		17)
			echo $i
			echo "bad luck from Italy"
			;;

		*)
			echo $i
			;;
	esac
	((i++))
done
