#!/usr/bin/env bash
# This script is displaying te hours every 60 minutes
i=0
j=1
while [ "$i" != 13 ]
do
	j=1
	echo "Hour: "$i
	if [ "$i" -lt 12 ]
	then
		while [ "$j" != 60 ]
		do
			echo $j
			((j++))
		done
	fi
	((i++))
done
