#!/usr/bin/env bash
# This script is displaying the hours every 60 minutes
i=0
j=1
while [ "$i" -le 12 ]
do
	j=1
	echo "Hour: "$i
	if [ "$i" -lt 12 ]
	then
		while [ "$j" -le 59 ]
		do
			echo "$j"
			((j++))
		done
	fi
	((i++))
done
