#!/usr/bin/env bash
# Configures an Ubuntu server
cp /etc/hosts /hosts.new
sed -i s/127.0.0.1/127.0.0.2/ /hosts.new
if grep "facebook.com" /hosts.new
then
	:
else
	echo -e "8.8.8.8\tfacebook.com" >> /hosts.new
fi
cat /hosts.new > /etc/hosts
